# coding: utf-8

"""
    Vapi API

    API for building voice assistants  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import vapi_python_client
from vapi_python_client.models.open_router_model import OpenRouterModel  # noqa: E501
from vapi_python_client.rest import ApiException


class TestOpenRouterModel(unittest.TestCase):
    """OpenRouterModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOpenRouterModel(self):
        """Test OpenRouterModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vapi_python_client.models.open_router_model.OpenRouterModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
