# coding: utf-8

"""
    Vapi API

    API for building voice assistants  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import vapi_python_client
from vapi_python_client.models.one_of_template_provider_details import OneOfTemplateProviderDetails  # noqa: E501
from vapi_python_client.rest import ApiException


class TestOneOfTemplateProviderDetails(unittest.TestCase):
    """OneOfTemplateProviderDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfTemplateProviderDetails(self):
        """Test OneOfTemplateProviderDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vapi_python_client.models.one_of_template_provider_details.OneOfTemplateProviderDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
