# coding: utf-8

"""
    Vapi API

    API for building voice assistants  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import vapi_python_client
from vapi_python_client.api.tools_api import ToolsApi  # noqa: E501
from vapi_python_client.rest import ApiException


class TestToolsApi(unittest.TestCase):
    """ToolsApi unit test stubs"""

    def setUp(self):
        self.api = ToolsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_tool_controller_create(self):
        """Test case for tool_controller_create

        Create Tool  # noqa: E501
        """
        pass

    def test_tool_controller_find_all(self):
        """Test case for tool_controller_find_all

        List Tools  # noqa: E501
        """
        pass

    def test_tool_controller_find_one(self):
        """Test case for tool_controller_find_one

        Get Tool  # noqa: E501
        """
        pass

    def test_tool_controller_remove(self):
        """Test case for tool_controller_remove

        Delete Tool  # noqa: E501
        """
        pass

    def test_tool_controller_update(self):
        """Test case for tool_controller_update

        Update Tool  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
