# coding: utf-8

"""
    Vapi API

    API for building voice assistants  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import vapi_python_client
from vapi_python_client.models.create_end_call_tool_dto import CreateEndCallToolDTO  # noqa: E501
from vapi_python_client.rest import ApiException


class TestCreateEndCallToolDTO(unittest.TestCase):
    """CreateEndCallToolDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateEndCallToolDTO(self):
        """Test CreateEndCallToolDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vapi_python_client.models.create_end_call_tool_dto.CreateEndCallToolDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
