# coding: utf-8

"""
    Vapi API

    API for building voice assistants  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import vapi_python_client
from vapi_python_client.api.blocks_api import BlocksApi  # noqa: E501
from vapi_python_client.rest import ApiException


class TestBlocksApi(unittest.TestCase):
    """BlocksApi unit test stubs"""

    def setUp(self):
        self.api = BlocksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_block_controller_create(self):
        """Test case for block_controller_create

        Create Block  # noqa: E501
        """
        pass

    def test_block_controller_find_all(self):
        """Test case for block_controller_find_all

        List Blocks  # noqa: E501
        """
        pass

    def test_block_controller_find_one(self):
        """Test case for block_controller_find_one

        Get Block  # noqa: E501
        """
        pass

    def test_block_controller_remove(self):
        """Test case for block_controller_remove

        Delete Block  # noqa: E501
        """
        pass

    def test_block_controller_update(self):
        """Test case for block_controller_update

        Update Block  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
