# coding: utf-8

"""
    Vapi API

    API for building voice assistants  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import vapi_python_client
from vapi_python_client.models.client_inbound_message_add_message import ClientInboundMessageAddMessage  # noqa: E501
from vapi_python_client.rest import ApiException


class TestClientInboundMessageAddMessage(unittest.TestCase):
    """ClientInboundMessageAddMessage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClientInboundMessageAddMessage(self):
        """Test ClientInboundMessageAddMessage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vapi_python_client.models.client_inbound_message_add_message.ClientInboundMessageAddMessage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
