# coding: utf-8

"""
    Vapi API

    API for building voice assistants  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import vapi_python_client
from vapi_python_client.models.create_byo_sip_trunk_credential_dto import CreateByoSipTrunkCredentialDTO  # noqa: E501
from vapi_python_client.rest import ApiException


class TestCreateByoSipTrunkCredentialDTO(unittest.TestCase):
    """CreateByoSipTrunkCredentialDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateByoSipTrunkCredentialDTO(self):
        """Test CreateByoSipTrunkCredentialDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vapi_python_client.models.create_byo_sip_trunk_credential_dto.CreateByoSipTrunkCredentialDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
