# coding: utf-8

"""
    Vapi API

    API for building voice assistants  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AnalyticsOperation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'operation': 'str',
        'column': 'str',
        'alias': 'str'
    }

    attribute_map = {
        'operation': 'operation',
        'column': 'column',
        'alias': 'alias'
    }

    def __init__(self, operation=None, column=None, alias=None):  # noqa: E501
        """AnalyticsOperation - a model defined in Swagger"""  # noqa: E501
        self._operation = None
        self._column = None
        self._alias = None
        self.discriminator = None
        self.operation = operation
        self.column = column
        if alias is not None:
            self.alias = alias

    @property
    def operation(self):
        """Gets the operation of this AnalyticsOperation.  # noqa: E501

        This is the aggregation operation you want to perform.  # noqa: E501

        :return: The operation of this AnalyticsOperation.  # noqa: E501
        :rtype: str
        """
        return self._operation

    @operation.setter
    def operation(self, operation):
        """Sets the operation of this AnalyticsOperation.

        This is the aggregation operation you want to perform.  # noqa: E501

        :param operation: The operation of this AnalyticsOperation.  # noqa: E501
        :type: str
        """
        if operation is None:
            raise ValueError("Invalid value for `operation`, must not be `None`")  # noqa: E501
        allowed_values = ["sum", "avg", "count", "min", "max"]  # noqa: E501
        if operation not in allowed_values:
            raise ValueError(
                "Invalid value for `operation` ({0}), must be one of {1}"  # noqa: E501
                .format(operation, allowed_values)
            )

        self._operation = operation

    @property
    def column(self):
        """Gets the column of this AnalyticsOperation.  # noqa: E501

        This is the columns you want to perform the aggregation operation on.  # noqa: E501

        :return: The column of this AnalyticsOperation.  # noqa: E501
        :rtype: str
        """
        return self._column

    @column.setter
    def column(self, column):
        """Sets the column of this AnalyticsOperation.

        This is the columns you want to perform the aggregation operation on.  # noqa: E501

        :param column: The column of this AnalyticsOperation.  # noqa: E501
        :type: str
        """
        if column is None:
            raise ValueError("Invalid value for `column`, must not be `None`")  # noqa: E501
        allowed_values = ["id", "cost", "costBreakdown.llm", "costBreakdown.stt", "costBreakdown.tts", "costBreakdown.vapi", "costBreakdown.ttsCharacters", "costBreakdown.llmPromptTokens", "costBreakdown.llmCompletionTokens", "duration"]  # noqa: E501
        if column not in allowed_values:
            raise ValueError(
                "Invalid value for `column` ({0}), must be one of {1}"  # noqa: E501
                .format(column, allowed_values)
            )

        self._column = column

    @property
    def alias(self):
        """Gets the alias of this AnalyticsOperation.  # noqa: E501

        This is the alias for column name returned. Defaults to `${operation}${column}`.  # noqa: E501

        :return: The alias of this AnalyticsOperation.  # noqa: E501
        :rtype: str
        """
        return self._alias

    @alias.setter
    def alias(self, alias):
        """Sets the alias of this AnalyticsOperation.

        This is the alias for column name returned. Defaults to `${operation}${column}`.  # noqa: E501

        :param alias: The alias of this AnalyticsOperation.  # noqa: E501
        :type: str
        """

        self._alias = alias

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AnalyticsOperation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AnalyticsOperation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
