# coding: utf-8

"""
    Vapi API

    API for building voice assistants  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ClientInboundMessageSay(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'content': 'str',
        'end_call_after_spoken': 'bool'
    }

    attribute_map = {
        'type': 'type',
        'content': 'content',
        'end_call_after_spoken': 'endCallAfterSpoken'
    }

    def __init__(self, type=None, content=None, end_call_after_spoken=None):  # noqa: E501
        """ClientInboundMessageSay - a model defined in Swagger"""  # noqa: E501
        self._type = None
        self._content = None
        self._end_call_after_spoken = None
        self.discriminator = None
        if type is not None:
            self.type = type
        if content is not None:
            self.content = content
        if end_call_after_spoken is not None:
            self.end_call_after_spoken = end_call_after_spoken

    @property
    def type(self):
        """Gets the type of this ClientInboundMessageSay.  # noqa: E501

        This is the type of the message. Send \"say\" message to make the assistant say something.  # noqa: E501

        :return: The type of this ClientInboundMessageSay.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ClientInboundMessageSay.

        This is the type of the message. Send \"say\" message to make the assistant say something.  # noqa: E501

        :param type: The type of this ClientInboundMessageSay.  # noqa: E501
        :type: str
        """
        allowed_values = ["say"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def content(self):
        """Gets the content of this ClientInboundMessageSay.  # noqa: E501

        This is the content to say.  # noqa: E501

        :return: The content of this ClientInboundMessageSay.  # noqa: E501
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this ClientInboundMessageSay.

        This is the content to say.  # noqa: E501

        :param content: The content of this ClientInboundMessageSay.  # noqa: E501
        :type: str
        """

        self._content = content

    @property
    def end_call_after_spoken(self):
        """Gets the end_call_after_spoken of this ClientInboundMessageSay.  # noqa: E501

        This is the flag to end call after content is spoken.  # noqa: E501

        :return: The end_call_after_spoken of this ClientInboundMessageSay.  # noqa: E501
        :rtype: bool
        """
        return self._end_call_after_spoken

    @end_call_after_spoken.setter
    def end_call_after_spoken(self, end_call_after_spoken):
        """Sets the end_call_after_spoken of this ClientInboundMessageSay.

        This is the flag to end call after content is spoken.  # noqa: E501

        :param end_call_after_spoken: The end_call_after_spoken of this ClientInboundMessageSay.  # noqa: E501
        :type: bool
        """

        self._end_call_after_spoken = end_call_after_spoken

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ClientInboundMessageSay, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ClientInboundMessageSay):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
