# coding: utf-8

"""
    Vapi API

    API for building voice assistants  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MakeToolProviderDetails(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'template_url': 'str',
        'setup_instructions': 'list[ToolTemplateSetup]',
        'type': 'str',
        'scenario_id': 'float',
        'scenario_name': 'str',
        'trigger_hook_id': 'float',
        'trigger_hook_name': 'str'
    }

    attribute_map = {
        'template_url': 'templateUrl',
        'setup_instructions': 'setupInstructions',
        'type': 'type',
        'scenario_id': 'scenarioId',
        'scenario_name': 'scenarioName',
        'trigger_hook_id': 'triggerHookId',
        'trigger_hook_name': 'triggerHookName'
    }

    def __init__(self, template_url=None, setup_instructions=None, type=None, scenario_id=None, scenario_name=None, trigger_hook_id=None, trigger_hook_name=None):  # noqa: E501
        """MakeToolProviderDetails - a model defined in Swagger"""  # noqa: E501
        self._template_url = None
        self._setup_instructions = None
        self._type = None
        self._scenario_id = None
        self._scenario_name = None
        self._trigger_hook_id = None
        self._trigger_hook_name = None
        self.discriminator = None
        if template_url is not None:
            self.template_url = template_url
        if setup_instructions is not None:
            self.setup_instructions = setup_instructions
        self.type = type
        if scenario_id is not None:
            self.scenario_id = scenario_id
        if scenario_name is not None:
            self.scenario_name = scenario_name
        if trigger_hook_id is not None:
            self.trigger_hook_id = trigger_hook_id
        if trigger_hook_name is not None:
            self.trigger_hook_name = trigger_hook_name

    @property
    def template_url(self):
        """Gets the template_url of this MakeToolProviderDetails.  # noqa: E501

        This is the Template URL or the Snapshot URL corresponding to the Template.  # noqa: E501

        :return: The template_url of this MakeToolProviderDetails.  # noqa: E501
        :rtype: str
        """
        return self._template_url

    @template_url.setter
    def template_url(self, template_url):
        """Sets the template_url of this MakeToolProviderDetails.

        This is the Template URL or the Snapshot URL corresponding to the Template.  # noqa: E501

        :param template_url: The template_url of this MakeToolProviderDetails.  # noqa: E501
        :type: str
        """

        self._template_url = template_url

    @property
    def setup_instructions(self):
        """Gets the setup_instructions of this MakeToolProviderDetails.  # noqa: E501


        :return: The setup_instructions of this MakeToolProviderDetails.  # noqa: E501
        :rtype: list[ToolTemplateSetup]
        """
        return self._setup_instructions

    @setup_instructions.setter
    def setup_instructions(self, setup_instructions):
        """Sets the setup_instructions of this MakeToolProviderDetails.


        :param setup_instructions: The setup_instructions of this MakeToolProviderDetails.  # noqa: E501
        :type: list[ToolTemplateSetup]
        """

        self._setup_instructions = setup_instructions

    @property
    def type(self):
        """Gets the type of this MakeToolProviderDetails.  # noqa: E501

        The type of tool. \"make\" for Make tool.  # noqa: E501

        :return: The type of this MakeToolProviderDetails.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this MakeToolProviderDetails.

        The type of tool. \"make\" for Make tool.  # noqa: E501

        :param type: The type of this MakeToolProviderDetails.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501
        allowed_values = ["make"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def scenario_id(self):
        """Gets the scenario_id of this MakeToolProviderDetails.  # noqa: E501


        :return: The scenario_id of this MakeToolProviderDetails.  # noqa: E501
        :rtype: float
        """
        return self._scenario_id

    @scenario_id.setter
    def scenario_id(self, scenario_id):
        """Sets the scenario_id of this MakeToolProviderDetails.


        :param scenario_id: The scenario_id of this MakeToolProviderDetails.  # noqa: E501
        :type: float
        """

        self._scenario_id = scenario_id

    @property
    def scenario_name(self):
        """Gets the scenario_name of this MakeToolProviderDetails.  # noqa: E501


        :return: The scenario_name of this MakeToolProviderDetails.  # noqa: E501
        :rtype: str
        """
        return self._scenario_name

    @scenario_name.setter
    def scenario_name(self, scenario_name):
        """Sets the scenario_name of this MakeToolProviderDetails.


        :param scenario_name: The scenario_name of this MakeToolProviderDetails.  # noqa: E501
        :type: str
        """

        self._scenario_name = scenario_name

    @property
    def trigger_hook_id(self):
        """Gets the trigger_hook_id of this MakeToolProviderDetails.  # noqa: E501


        :return: The trigger_hook_id of this MakeToolProviderDetails.  # noqa: E501
        :rtype: float
        """
        return self._trigger_hook_id

    @trigger_hook_id.setter
    def trigger_hook_id(self, trigger_hook_id):
        """Sets the trigger_hook_id of this MakeToolProviderDetails.


        :param trigger_hook_id: The trigger_hook_id of this MakeToolProviderDetails.  # noqa: E501
        :type: float
        """

        self._trigger_hook_id = trigger_hook_id

    @property
    def trigger_hook_name(self):
        """Gets the trigger_hook_name of this MakeToolProviderDetails.  # noqa: E501


        :return: The trigger_hook_name of this MakeToolProviderDetails.  # noqa: E501
        :rtype: str
        """
        return self._trigger_hook_name

    @trigger_hook_name.setter
    def trigger_hook_name(self, trigger_hook_name):
        """Sets the trigger_hook_name of this MakeToolProviderDetails.


        :param trigger_hook_name: The trigger_hook_name of this MakeToolProviderDetails.  # noqa: E501
        :type: str
        """

        self._trigger_hook_name = trigger_hook_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MakeToolProviderDetails, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MakeToolProviderDetails):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
