# coding: utf-8

"""
    Vapi API

    API for building voice assistants  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ToolTemplateSetup(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'title': 'str',
        'description': 'str',
        'video_url': 'str',
        'docs_url': 'str'
    }

    attribute_map = {
        'title': 'title',
        'description': 'description',
        'video_url': 'videoUrl',
        'docs_url': 'docsUrl'
    }

    def __init__(self, title=None, description=None, video_url=None, docs_url=None):  # noqa: E501
        """ToolTemplateSetup - a model defined in Swagger"""  # noqa: E501
        self._title = None
        self._description = None
        self._video_url = None
        self._docs_url = None
        self.discriminator = None
        self.title = title
        if description is not None:
            self.description = description
        if video_url is not None:
            self.video_url = video_url
        if docs_url is not None:
            self.docs_url = docs_url

    @property
    def title(self):
        """Gets the title of this ToolTemplateSetup.  # noqa: E501


        :return: The title of this ToolTemplateSetup.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this ToolTemplateSetup.


        :param title: The title of this ToolTemplateSetup.  # noqa: E501
        :type: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def description(self):
        """Gets the description of this ToolTemplateSetup.  # noqa: E501


        :return: The description of this ToolTemplateSetup.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ToolTemplateSetup.


        :param description: The description of this ToolTemplateSetup.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def video_url(self):
        """Gets the video_url of this ToolTemplateSetup.  # noqa: E501


        :return: The video_url of this ToolTemplateSetup.  # noqa: E501
        :rtype: str
        """
        return self._video_url

    @video_url.setter
    def video_url(self, video_url):
        """Sets the video_url of this ToolTemplateSetup.


        :param video_url: The video_url of this ToolTemplateSetup.  # noqa: E501
        :type: str
        """

        self._video_url = video_url

    @property
    def docs_url(self):
        """Gets the docs_url of this ToolTemplateSetup.  # noqa: E501


        :return: The docs_url of this ToolTemplateSetup.  # noqa: E501
        :rtype: str
        """
        return self._docs_url

    @docs_url.setter
    def docs_url(self, docs_url):
        """Sets the docs_url of this ToolTemplateSetup.


        :param docs_url: The docs_url of this ToolTemplateSetup.  # noqa: E501
        :type: str
        """

        self._docs_url = docs_url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ToolTemplateSetup, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ToolTemplateSetup):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
