# coding: utf-8

"""
    Vapi API

    API for building voice assistants  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UpdateByoSipTrunkCredentialDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'provider': 'str',
        'gateways': 'list[SipTrunkGateway]',
        'name': 'str',
        'outbound_authentication_plan': 'AllOfUpdateByoSipTrunkCredentialDTOOutboundAuthenticationPlan',
        'sbc_configuration': 'AllOfUpdateByoSipTrunkCredentialDTOSbcConfiguration'
    }

    attribute_map = {
        'provider': 'provider',
        'gateways': 'gateways',
        'name': 'name',
        'outbound_authentication_plan': 'outboundAuthenticationPlan',
        'sbc_configuration': 'sbcConfiguration'
    }

    def __init__(self, provider=None, gateways=None, name=None, outbound_authentication_plan=None, sbc_configuration=None):  # noqa: E501
        """UpdateByoSipTrunkCredentialDTO - a model defined in Swagger"""  # noqa: E501
        self._provider = None
        self._gateways = None
        self._name = None
        self._outbound_authentication_plan = None
        self._sbc_configuration = None
        self.discriminator = None
        if provider is not None:
            self.provider = provider
        self.gateways = gateways
        if name is not None:
            self.name = name
        if outbound_authentication_plan is not None:
            self.outbound_authentication_plan = outbound_authentication_plan
        if sbc_configuration is not None:
            self.sbc_configuration = sbc_configuration

    @property
    def provider(self):
        """Gets the provider of this UpdateByoSipTrunkCredentialDTO.  # noqa: E501

        This can be used to bring your own SIP trunks or to connect to a Carrier.  # noqa: E501

        :return: The provider of this UpdateByoSipTrunkCredentialDTO.  # noqa: E501
        :rtype: str
        """
        return self._provider

    @provider.setter
    def provider(self, provider):
        """Sets the provider of this UpdateByoSipTrunkCredentialDTO.

        This can be used to bring your own SIP trunks or to connect to a Carrier.  # noqa: E501

        :param provider: The provider of this UpdateByoSipTrunkCredentialDTO.  # noqa: E501
        :type: str
        """
        allowed_values = ["byo-sip-trunk"]  # noqa: E501
        if provider not in allowed_values:
            raise ValueError(
                "Invalid value for `provider` ({0}), must be one of {1}"  # noqa: E501
                .format(provider, allowed_values)
            )

        self._provider = provider

    @property
    def gateways(self):
        """Gets the gateways of this UpdateByoSipTrunkCredentialDTO.  # noqa: E501

        This is the list of SIP trunk's gateways.  # noqa: E501

        :return: The gateways of this UpdateByoSipTrunkCredentialDTO.  # noqa: E501
        :rtype: list[SipTrunkGateway]
        """
        return self._gateways

    @gateways.setter
    def gateways(self, gateways):
        """Sets the gateways of this UpdateByoSipTrunkCredentialDTO.

        This is the list of SIP trunk's gateways.  # noqa: E501

        :param gateways: The gateways of this UpdateByoSipTrunkCredentialDTO.  # noqa: E501
        :type: list[SipTrunkGateway]
        """
        if gateways is None:
            raise ValueError("Invalid value for `gateways`, must not be `None`")  # noqa: E501

        self._gateways = gateways

    @property
    def name(self):
        """Gets the name of this UpdateByoSipTrunkCredentialDTO.  # noqa: E501

        This is the name of the SIP trunk. This is just for your reference.  # noqa: E501

        :return: The name of this UpdateByoSipTrunkCredentialDTO.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this UpdateByoSipTrunkCredentialDTO.

        This is the name of the SIP trunk. This is just for your reference.  # noqa: E501

        :param name: The name of this UpdateByoSipTrunkCredentialDTO.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def outbound_authentication_plan(self):
        """Gets the outbound_authentication_plan of this UpdateByoSipTrunkCredentialDTO.  # noqa: E501

        This can be used to configure the outbound authentication if required by the SIP trunk.  # noqa: E501

        :return: The outbound_authentication_plan of this UpdateByoSipTrunkCredentialDTO.  # noqa: E501
        :rtype: AllOfUpdateByoSipTrunkCredentialDTOOutboundAuthenticationPlan
        """
        return self._outbound_authentication_plan

    @outbound_authentication_plan.setter
    def outbound_authentication_plan(self, outbound_authentication_plan):
        """Sets the outbound_authentication_plan of this UpdateByoSipTrunkCredentialDTO.

        This can be used to configure the outbound authentication if required by the SIP trunk.  # noqa: E501

        :param outbound_authentication_plan: The outbound_authentication_plan of this UpdateByoSipTrunkCredentialDTO.  # noqa: E501
        :type: AllOfUpdateByoSipTrunkCredentialDTOOutboundAuthenticationPlan
        """

        self._outbound_authentication_plan = outbound_authentication_plan

    @property
    def sbc_configuration(self):
        """Gets the sbc_configuration of this UpdateByoSipTrunkCredentialDTO.  # noqa: E501

        This is an advanced configuration for enterprise deployments. This uses the onprem SBC to trunk into the SIP trunk's `gateways`, rather than the managed SBC provided by Vapi.  # noqa: E501

        :return: The sbc_configuration of this UpdateByoSipTrunkCredentialDTO.  # noqa: E501
        :rtype: AllOfUpdateByoSipTrunkCredentialDTOSbcConfiguration
        """
        return self._sbc_configuration

    @sbc_configuration.setter
    def sbc_configuration(self, sbc_configuration):
        """Sets the sbc_configuration of this UpdateByoSipTrunkCredentialDTO.

        This is an advanced configuration for enterprise deployments. This uses the onprem SBC to trunk into the SIP trunk's `gateways`, rather than the managed SBC provided by Vapi.  # noqa: E501

        :param sbc_configuration: The sbc_configuration of this UpdateByoSipTrunkCredentialDTO.  # noqa: E501
        :type: AllOfUpdateByoSipTrunkCredentialDTOSbcConfiguration
        """

        self._sbc_configuration = sbc_configuration

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpdateByoSipTrunkCredentialDTO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateByoSipTrunkCredentialDTO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
