# coding: utf-8

"""
    Vapi API

    API for building voice assistants  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UpdateMakeCredentialDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'provider': 'str',
        'team_id': 'str',
        'region': 'str',
        'api_key': 'str'
    }

    attribute_map = {
        'provider': 'provider',
        'team_id': 'teamId',
        'region': 'region',
        'api_key': 'apiKey'
    }

    def __init__(self, provider=None, team_id=None, region=None, api_key=None):  # noqa: E501
        """UpdateMakeCredentialDTO - a model defined in Swagger"""  # noqa: E501
        self._provider = None
        self._team_id = None
        self._region = None
        self._api_key = None
        self.discriminator = None
        self.provider = provider
        self.team_id = team_id
        self.region = region
        self.api_key = api_key

    @property
    def provider(self):
        """Gets the provider of this UpdateMakeCredentialDTO.  # noqa: E501


        :return: The provider of this UpdateMakeCredentialDTO.  # noqa: E501
        :rtype: str
        """
        return self._provider

    @provider.setter
    def provider(self, provider):
        """Sets the provider of this UpdateMakeCredentialDTO.


        :param provider: The provider of this UpdateMakeCredentialDTO.  # noqa: E501
        :type: str
        """
        if provider is None:
            raise ValueError("Invalid value for `provider`, must not be `None`")  # noqa: E501
        allowed_values = ["make"]  # noqa: E501
        if provider not in allowed_values:
            raise ValueError(
                "Invalid value for `provider` ({0}), must be one of {1}"  # noqa: E501
                .format(provider, allowed_values)
            )

        self._provider = provider

    @property
    def team_id(self):
        """Gets the team_id of this UpdateMakeCredentialDTO.  # noqa: E501

        Team ID  # noqa: E501

        :return: The team_id of this UpdateMakeCredentialDTO.  # noqa: E501
        :rtype: str
        """
        return self._team_id

    @team_id.setter
    def team_id(self, team_id):
        """Sets the team_id of this UpdateMakeCredentialDTO.

        Team ID  # noqa: E501

        :param team_id: The team_id of this UpdateMakeCredentialDTO.  # noqa: E501
        :type: str
        """
        if team_id is None:
            raise ValueError("Invalid value for `team_id`, must not be `None`")  # noqa: E501

        self._team_id = team_id

    @property
    def region(self):
        """Gets the region of this UpdateMakeCredentialDTO.  # noqa: E501

        Region of your application. For example: eu1, eu2, us1, us2  # noqa: E501

        :return: The region of this UpdateMakeCredentialDTO.  # noqa: E501
        :rtype: str
        """
        return self._region

    @region.setter
    def region(self, region):
        """Sets the region of this UpdateMakeCredentialDTO.

        Region of your application. For example: eu1, eu2, us1, us2  # noqa: E501

        :param region: The region of this UpdateMakeCredentialDTO.  # noqa: E501
        :type: str
        """
        if region is None:
            raise ValueError("Invalid value for `region`, must not be `None`")  # noqa: E501

        self._region = region

    @property
    def api_key(self):
        """Gets the api_key of this UpdateMakeCredentialDTO.  # noqa: E501

        This is not returned in the API.  # noqa: E501

        :return: The api_key of this UpdateMakeCredentialDTO.  # noqa: E501
        :rtype: str
        """
        return self._api_key

    @api_key.setter
    def api_key(self, api_key):
        """Sets the api_key of this UpdateMakeCredentialDTO.

        This is not returned in the API.  # noqa: E501

        :param api_key: The api_key of this UpdateMakeCredentialDTO.  # noqa: E501
        :type: str
        """
        if api_key is None:
            raise ValueError("Invalid value for `api_key`, must not be `None`")  # noqa: E501

        self._api_key = api_key

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpdateMakeCredentialDTO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateMakeCredentialDTO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
